### ISSUE TITLE
[sdk] Make it possible for SDK users to access the canonical version

### ISSUE THREAD

**Issue by charlieegan3** [open-policy-agent/regal#322]
In OPA, the version is available in the [code](https://github.com/open-policy-agent/opa/blob/main/version/version.go#L14). It'd be nice to have similar data available when using Regal.

Currently, the version is only [set for the binary](https://github.com/StyraInc/regal/blob/main/pkg/version/version.go#L14) at build time.

**Comment by srenatus** [comment]
It is perhaps easier today to do this via [`debug.Buildinfo()`](https://pkg.go.dev/runtime/debug#BuildInfo). It seems to have all the deps, too: https://pkg.go.dev/runtime/debug#Module

**Comment by charlieegan3** [comment]
Hmm, that probably is the best option. I wasn't aware of such a feature!

I'll close this for now.
